name:                 2Dgame
version:              0.1.0.0
visibility:           public
id:                   2Dgame-0.1.0.0-inplace
key:                  2Dgame-0.1.0.0-inplace
license:              BSD-3-Clause
maintainer:           kristapsdubra11@gmail.com
author:               mem10l
abi:                  inplace
exposed:              True
exposed-modules:      MyLib
import-dirs:
    /home/mem10l/28.04.2026/forfun/2Dgame/dist-newstyle/build/x86_64-linux/ghc-9.6.7/2Dgame-0.1.0.0/build

library-dirs:
    /home/mem10l/28.04.2026/forfun/2Dgame/dist-newstyle/build/x86_64-linux/ghc-9.6.7/2Dgame-0.1.0.0/build

library-dirs-static:
    /home/mem10l/28.04.2026/forfun/2Dgame/dist-newstyle/build/x86_64-linux/ghc-9.6.7/2Dgame-0.1.0.0/build

dynamic-library-dirs:
    /home/mem10l/28.04.2026/forfun/2Dgame/dist-newstyle/build/x86_64-linux/ghc-9.6.7/2Dgame-0.1.0.0/build

data-dir:             /home/mem10l/28.04.2026/forfun/2Dgame/.
hs-libraries:         HS2Dgame-0.1.0.0-inplace
depends:
    base-4.18.3.0
    gloss-1.13.2.2-f2179fe4f0ce2e6ed3174f440663d2f469479d3b7f8ff1bcd8de2270f307c772

haddock-interfaces:
    /home/mem10l/28.04.2026/forfun/2Dgame/dist-newstyle/build/x86_64-linux/ghc-9.6.7/2Dgame-0.1.0.0/doc/html/2Dgame/2Dgame.haddock

haddock-html:
    /home/mem10l/28.04.2026/forfun/2Dgame/dist-newstyle/build/x86_64-linux/ghc-9.6.7/2Dgame-0.1.0.0/doc/html/2Dgame
